### PR TITLE
fix: support null insert

### LINKED ISSUE #386: bug: NULL insert
Related to #376

At v0.2.0:

```sql
CREATE TABLE t (val vector(3));
INSERT INTO t (val) VALUES (NULL);
CREATE INDEX ON t USING vectors (val vector_l2_ops)
WITH (options = "[indexing.hnsw]");
```

```bash
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
The connection to the server was lost. Attempting reset: Failed.
```

### PR DESCRIPTION
**Pull request by cutecutecat**
Fix #386 
Part of #376 , we still need a patch for upgrade to v0.2.0

### CODE REVIEW

File: src/index/utils.rs [hunk 1]
```diff
@@ -12,21 +12,24 @@ struct Header {
     kind: u16,
 }
 
-pub unsafe fn from_datum(datum: pgrx::pg_sys::Datum) -> OwnedVector {
+pub unsafe fn from_datum(datum: pgrx::pg_sys::Datum) -> Option<OwnedVector> {
```
Comment (usamoi) [inline src/index/utils.rs:15]:
```suggestion
pub unsafe fn from_datum(values: pgrx::pg_sys::Datum, is_null: bool) -> Option<OwnedVector> {
```

File: src/index/am_build.rs [hunk 2]
```diff
@@ -57,13 +57,21 @@ unsafe extern "C" fn callback(
     _tuple_is_alive: bool,
     state: *mut std::os::raw::c_void,
 ) {
+    let state = &mut *(state as *mut Builder);
+    if *_is_null.add(0) {
```
Comment (usamoi) [inline src/index/am_build.rs:61]: Undefine is for suppressing `dead_code` warning. Since we use it now, remove it.

**Review by usamoi — APPROVED** [review]

**Comment by VoVAllen** [comment]
Please cherry pick this into 0.2 branch
